import React, { useState } from 'react';
import { AppState } from '@/src/types';
import { Card, CardTitle } from '../ui/Card';
import { Button } from '../ui/Button';
import { FileText, Download, RotateCcw, Eye } from 'lucide-react';
import { cn } from '@/src/lib/utils';

interface StepProps {
  state: AppState;
  updateState: (updates: Partial<AppState>) => void;
  onPrev: () => void;
  onReset: () => void;
}

export const FinalReport: React.FC<StepProps> = ({ state, onPrev, onReset }) => {
  const { lang } = state;
  const [showPreview, setShowPreview] = useState(false);

  const generateReportText = () => {
    const zh = lang === 'zh';
    const date = new Date().toLocaleDateString();
    
    let text = `
==================================================
${zh ? 'AI 多學科美國大學申請策略 · 完整分析報告' : 'AI Multi-Discipline U.S. College Strategy Report'}
==================================================
Generated: ${date}

1. ${zh ? '學生基本資料' : 'Student Profile'}
--------------------------------------------------
SAT: ${state.satScore} (Math: ${state.satMath})
GPA: ${state.gpaU} (${state.gpaScale})
${zh ? '主修' : 'Majors'}: ${state.selectedDiscs.join(', ')}
${zh ? '活動' : 'Activities'}: ${state.activities.length} ${zh ? '項' : 'items'}

2. ${zh ? 'AI 申請策略' : 'AI Strategy Plan'}
--------------------------------------------------
${state.aiStrategy || (zh ? '尚未生成策略' : 'Strategy not generated')}

3. ${zh ? '家庭決策對齊' : 'Family Alignment'}
--------------------------------------------------
${zh ? '對齊分數' : 'Alignment Score'}: ${state.familyPriorities.student.interest} / 10

4. ${zh ? '目標學校' : 'Target Schools'}
--------------------------------------------------
${state.customSchools.map(s => `• ${s.name} (${s.accept}% accept)`).join('\n')}

==================================================
${zh ? '本報告由 AI 多學科大學申請平台自動生成' : 'Generated by AI Multi-Discipline Admissions Platform'}
==================================================
`;
    return text.trim();
  };

  const handleDownload = () => {
    const text = generateReportText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = lang === 'zh' ? '申請策略報告.txt' : 'Admissions_Report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="space-y-1">
        <h2 className="text-2xl font-extrabold bg-gradient-to-r from-white to-blue-400 bg-clip-text text-transparent">
          {lang === 'zh' ? '生成完整申請分析報告' : 'Generate Comprehensive Admission Report'}
        </h2>
        <p className="text-sm text-slate-400">
          {lang === 'zh' ? '彙整您的全部資料與 AI 分析，生成一份完整的跨學科申請策略報告。' : 'Compile all your data and AI insights into a comprehensive cross-discipline admission strategy report.'}
        </p>
      </div>

      <div className="flex flex-col md:flex-row gap-4 justify-center py-8">
        <Button variant="purple" size="lg" className="h-16 px-8 text-lg" onClick={() => setShowPreview(!showPreview)}>
          <Eye className="w-6 h-6" />
          {lang === 'zh' ? '預覽報告' : 'Preview Report'}
        </Button>
        <Button variant="gold" size="lg" className="h-16 px-8 text-lg" onClick={handleDownload}>
          <Download className="w-6 h-6" />
          {lang === 'zh' ? '下載報告 (.txt)' : 'Download Report (.txt)'}
        </Button>
      </div>

      {showPreview && (
        <Card className="animate-in fade-in slide-in-from-bottom-4 duration-500">
          <CardTitle><FileText className="w-4 h-4" /> {lang === 'zh' ? '報告預覽' : 'Report Preview'}</CardTitle>
          <pre className="whitespace-pre-wrap font-mono text-xs text-slate-300 bg-black/40 p-6 rounded-xl border border-white/5 leading-relaxed overflow-x-auto">
            {generateReportText()}
          </pre>
        </Card>
      )}

      <div className="flex justify-between pt-4">
        <Button variant="secondary" size="lg" onClick={onPrev}>
          ← {lang === 'zh' ? '上一步' : 'Back'}
        </Button>
        <Button variant="green" size="lg" onClick={onReset}>
          <RotateCcw className="w-4 h-4" />
          {lang === 'zh' ? '重新開始' : 'Start Over'}
        </Button>
      </div>
    </div>
  );
};
